version: '3.8'
services:
  database:
    container_name: database
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: bbdd
      POSTGRES_USER: api
      POSTGRES_PASSWORD: password
  code:
    build: .
    ports:
      - "8000:8000"
    links:
      - database
    volumes:
      - .:/code
    depends_on:
      - database
    environment:
      - PORT=8000
    command: /bin/bash -c "/code/scripts/wait/tcp.sh database 5432 &&
                           /code/scripts/settings/docker.sh &&
                           /code/scripts/venv.sh &&
                           /code/scripts/migrate.sh &&
                           /code/scripts/seed.sh &&
                           /code/scripts/run.sh"
  code-bash:
    build: .
    ports:
      - "8000:8000"
    links:
      - database
    volumes:
      - .:/code
    depends_on:
      - database
    environment:
      - PORT=8000
    command: /bin/bash -c "/code/scripts/wait/tcp.sh database 5432 &&
                           /code/scripts/settings/docker.sh &&
                           /code/scripts/venv.sh &&
                           /code/scripts/migrate.sh &&
                           /code/scripts/seed.sh &&
                           /bin/bash"
  code-test:
    build: .
    ports:
      - "8000:8000"
    links:
      - database
    depends_on:
      - database
    environment:
      - PORT=8000
    command: /bin/bash -c "/code/scripts/wait/tcp.sh database 5432 &&
                           /code/scripts/settings/docker.sh &&
                           /code/scripts/venv.sh &&
                           /code/scripts/migrate.sh &&
                           /code/scripts/test.sh"
